version: '3'
services:
  customer:
    build: ./customer
    image: customer
    ports:
      - "4000:3000"
    networks:
      - westfield_mall
  burgerqueen:
    build: ./burgerqueen
    image: burgerqueen
    networks:
      - westfield_mall
  hobos:
    build: ./hobos
    image: hobos
    networks:
      - westfield_mall
  iowafried:
    build: ./iowafried
    image: iowafried
    networks:
      - westfield_mall
networks:
  westfield_mall:
