version: '3'
services:
  customer:
    image: localhost:5000/customer
    depends_on:
      - burgerqueen
      - hobos
      - iowafried
    ports:
      - "4000:3000"
    networks:
      - westfield_mall
  burgerqueen:
    image: localhost:5000/burgerqueen
    networks:
      - westfield_mall
  hobos:
    image: localhost:5000/hobos
    networks:
      - westfield_mall
  iowafried:
    image: localhost:5000/iowafried
    networks:
      - westfield_mall
networks:
  westfield_mall:
