version: '3'
services:
  customer:
    build: ./customer
    ports:
      - "4000:3000"
    networks:
      - westfield_mall
    depends_on:
      - jaeger
  burgerqueen:
    build: ./burgerqueen
    networks:
      - westfield_mall
    depends_on:
      - jaeger
  hobos:
    build: ./hobos
    networks:
      - westfield_mall
  iowafried:
    build: ./iowafried
    networks:
      - westfield_mall
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
    networks:
      - westfield_mall
networks:
  westfield_mall:
